version: '3.8'

services:
  postgres: 
    image: postgres:15
    container_name: taskhive-postgres
    ports:
      -"5432:5432"
    environment:
      POSTGRES_DB: taskhive
      POSTGRES_USER: saad
      POSTGRES_PASSWORD: securepass123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: 