version: '3.8'

services:
  postgres: 
    image: postgres:15
    container_name: taskhive-postgres
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: 